name: CD Pipeline

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull rohit0419121/cicd-pipeline:latest

    - name: Delete Old docker container
      run: sudo docker rm -f cicd-pipeline-container || true

    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name cicd-pipeline-container rohit0419121/cicd-pipeline:latest 